// ABOUTME: UTI constants for privacy-sensitive pasteboard markers.
// ABOUTME: Used to detect content that should not be recorded in clipboard history.

import AppKit

enum PasteboardConstants {
    /// Pasteboard types indicating content should be treated as private
    static let concealedMarkers: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        // 1Password
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        // KeePassXC
        NSPasteboard.PasteboardType("application/x-keepassxc-clipboard-protected"),
    ]
}
