// ABOUTME: Tests for ClipboardMonitor's static filtering logic.
// ABOUTME: Verifies privacy marker detection and excluded app filtering.

import XCTest
import AppKit
@testable import Stash

final class ClipboardMonitorTests: XCTestCase {

    // MARK: - shouldSkip with concealed markers

    func testSkipsConcealedType() {
        let types: [NSPasteboard.PasteboardType] = [
            .string,
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        ]
        XCTAssertTrue(ClipboardMonitor.shouldSkip(types: types, excludedBundleIDs: []))
    }

    func testSkipsTransientType() {
        let types: [NSPasteboard.PasteboardType] = [
            .string,
            NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        ]
        XCTAssertTrue(ClipboardMonitor.shouldSkip(types: types, excludedBundleIDs: []))
    }

    func testSkipsAutoGeneratedType() {
        let types: [NSPasteboard.PasteboardType] = [
            .string,
            NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        ]
        XCTAssertTrue(ClipboardMonitor.shouldSkip(types: types, excludedBundleIDs: []))
    }

    func testSkips1PasswordMarker() {
        let types: [NSPasteboard.PasteboardType] = [
            .string,
            NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        ]
        XCTAssertTrue(ClipboardMonitor.shouldSkip(types: types, excludedBundleIDs: []))
    }

    func testSkipsKeePassXCMarker() {
        let types: [NSPasteboard.PasteboardType] = [
            .string,
            NSPasteboard.PasteboardType("application/x-keepassxc-clipboard-protected"),
        ]
        XCTAssertTrue(ClipboardMonitor.shouldSkip(types: types, excludedBundleIDs: []))
    }

    func testDoesNotSkipNormalContent() {
        let types: [NSPasteboard.PasteboardType] = [.string]
        XCTAssertFalse(ClipboardMonitor.shouldSkip(types: types, excludedBundleIDs: []))
    }

    func testDoesNotSkipEmptyTypes() {
        XCTAssertFalse(ClipboardMonitor.shouldSkip(types: [], excludedBundleIDs: []))
    }

    // MARK: - Excluded apps

    func testSkipsExcludedApp() {
        let types: [NSPasteboard.PasteboardType] = [.string]
        XCTAssertTrue(
            ClipboardMonitor.shouldSkip(
                types: types,
                excludedBundleIDs: ["com.example.excluded"],
                frontmostBundleID: "com.example.excluded"
            )
        )
    }

    func testDoesNotSkipNonExcludedApp() {
        let types: [NSPasteboard.PasteboardType] = [.string]
        XCTAssertFalse(
            ClipboardMonitor.shouldSkip(
                types: types,
                excludedBundleIDs: ["com.example.excluded"],
                frontmostBundleID: "com.example.allowed"
            )
        )
    }

    func testDoesNotSkipWhenNoFrontmostApp() {
        let types: [NSPasteboard.PasteboardType] = [.string]
        XCTAssertFalse(
            ClipboardMonitor.shouldSkip(
                types: types,
                excludedBundleIDs: ["com.example.excluded"],
                frontmostBundleID: nil
            )
        )
    }
}
