name: Stash
options:
  bundleIdPrefix: com.hexul
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.38"
settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_HARDENED_RUNTIME: true
targets:
  Stash:
    type: application
    platform: macOS
    sources:
      - Stash
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hexul.Stash
        INFOPLIST_FILE: Stash/Info.plist
        CODE_SIGN_ENTITLEMENTS: Stash/Stash.entitlements
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_IDENTITY: "-"
        PRODUCT_NAME: Stash
    entitlements:
      path: Stash/Stash.entitlements
  StashTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - StashTests
    dependencies:
      - target: Stash
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hexul.StashTests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Stash.app/Contents/MacOS/Stash"
        BUNDLE_LOADER: "$(TEST_HOST)"
